# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: artimes_cv/protos/detector/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'artimes_cv/protos/detector/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'artimes_cv/protos/detector/common.proto\x12\tvision.v1\x1a\x1cgoogle/protobuf/struct.proto\"I\n\x0b\x42oundingBox\x12\r\n\x05x_min\x18\x01 \x01(\x02\x12\r\n\x05y_min\x18\x02 \x01(\x02\x12\r\n\x05x_max\x18\x03 \x01(\x02\x12\r\n\x05y_max\x18\x04 \x01(\x02\"\x1f\n\x07Point2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"<\n\x06\x43ircle\x12\"\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x12.vision.v1.Point2D\x12\x0e\n\x06radius\x18\x02 \x01(\x02\"\xb8\x01\n\x11\x44\x65tectionGeometry\x12%\n\x03\x62ox\x18\x01 \x01(\x0b\x32\x16.vision.v1.BoundingBoxH\x00\x12#\n\x05point\x18\x02 \x01(\x0b\x32\x12.vision.v1.Point2DH\x00\x12#\n\x06\x63ircle\x18\x03 \x01(\x0b\x32\x11.vision.v1.CircleH\x00\x12)\n\x06\x63ustom\x18\x04 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x42\x07\n\x05shape\"\xab\x01\n\tDetection\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x10\n\x08\x63lass_id\x18\x02 \x01(\x05\x12\r\n\x05score\x18\x03 \x01(\x02\x12.\n\x08geometry\x18\x04 \x01(\x0b\x32\x1c.vision.v1.DetectionGeometry\x12\x39\n\x13normalized_geometry\x18\x05 \x01(\x0b\x32\x1c.vision.v1.DetectionGeometry\"\x86\x01\n\x0cStreamConfig\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x13\n\x0bvideo_codec\x18\x02 \x01(\t\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12\x17\n\x0fscore_threshold\x18\x05 \x01(\x02\x12\x16\n\x0emax_detections\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'artimes_cv.protos.detector.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOUNDINGBOX']._serialized_start=84
  _globals['_BOUNDINGBOX']._serialized_end=157
  _globals['_POINT2D']._serialized_start=159
  _globals['_POINT2D']._serialized_end=190
  _globals['_CIRCLE']._serialized_start=192
  _globals['_CIRCLE']._serialized_end=252
  _globals['_DETECTIONGEOMETRY']._serialized_start=255
  _globals['_DETECTIONGEOMETRY']._serialized_end=439
  _globals['_DETECTION']._serialized_start=442
  _globals['_DETECTION']._serialized_end=613
  _globals['_STREAMCONFIG']._serialized_start=616
  _globals['_STREAMCONFIG']._serialized_end=750
# @@protoc_insertion_point(module_scope)
