# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from artemis_cv.protos.detector import detector_pb2 as artimes__cv_dot_protos_dot_detector_dot_detector__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in artimes_cv/protos/detector/detector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DetectorEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/vision.v1.DetectorEngine/Detect',
                request_serializer=artimes__cv_dot_protos_dot_detector_dot_detector__pb2.DetectRequest.SerializeToString,
                response_deserializer=artimes__cv_dot_protos_dot_detector_dot_detector__pb2.DetectReply.FromString,
                _registered_method=True)
        self.StreamDetect = channel.stream_stream(
                '/vision.v1.DetectorEngine/StreamDetect',
                request_serializer=artimes__cv_dot_protos_dot_detector_dot_detector__pb2.StreamDetectRequest.SerializeToString,
                response_deserializer=artimes__cv_dot_protos_dot_detector_dot_detector__pb2.StreamDetectReply.FromString,
                _registered_method=True)


class DetectorEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Detect(self, request, context):
        """输入单帧图像，返回该帧中的目标检测结果。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDetect(self, request_iterator, context):
        """输入连续视频流，持续返回该流中的目标检测结果。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectorEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=artimes__cv_dot_protos_dot_detector_dot_detector__pb2.DetectRequest.FromString,
                    response_serializer=artimes__cv_dot_protos_dot_detector_dot_detector__pb2.DetectReply.SerializeToString,
            ),
            'StreamDetect': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamDetect,
                    request_deserializer=artimes__cv_dot_protos_dot_detector_dot_detector__pb2.StreamDetectRequest.FromString,
                    response_serializer=artimes__cv_dot_protos_dot_detector_dot_detector__pb2.StreamDetectReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vision.v1.DetectorEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vision.v1.DetectorEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DetectorEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vision.v1.DetectorEngine/Detect',
            artimes__cv_dot_protos_dot_detector_dot_detector__pb2.DetectRequest.SerializeToString,
            artimes__cv_dot_protos_dot_detector_dot_detector__pb2.DetectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDetect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/vision.v1.DetectorEngine/StreamDetect',
            artimes__cv_dot_protos_dot_detector_dot_detector__pb2.StreamDetectRequest.SerializeToString,
            artimes__cv_dot_protos_dot_detector_dot_detector__pb2.StreamDetectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
