"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class BoundingBox(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    X_MIN_FIELD_NUMBER: _builtins.int
    Y_MIN_FIELD_NUMBER: _builtins.int
    X_MAX_FIELD_NUMBER: _builtins.int
    Y_MAX_FIELD_NUMBER: _builtins.int
    x_min: _builtins.float
    y_min: _builtins.float
    x_max: _builtins.float
    y_max: _builtins.float
    def __init__(
        self,
        *,
        x_min: _builtins.float = ...,
        y_min: _builtins.float = ...,
        x_max: _builtins.float = ...,
        y_max: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["x_max", b"x_max", "x_min", b"x_min", "y_max", b"y_max", "y_min", b"y_min"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BoundingBox: _TypeAlias = BoundingBox  # noqa: Y015

@_typing.final
class Point2D(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    x: _builtins.float
    y: _builtins.float
    def __init__(
        self,
        *,
        x: _builtins.float = ...,
        y: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["x", b"x", "y", b"y"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Point2D: _TypeAlias = Point2D  # noqa: Y015

@_typing.final
class Circle(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CENTER_FIELD_NUMBER: _builtins.int
    RADIUS_FIELD_NUMBER: _builtins.int
    radius: _builtins.float
    @_builtins.property
    def center(self) -> Global___Point2D: ...
    def __init__(
        self,
        *,
        center: Global___Point2D | None = ...,
        radius: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["center", b"center"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["center", b"center", "radius", b"radius"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Circle: _TypeAlias = Circle  # noqa: Y015

@_typing.final
class DetectionGeometry(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BOX_FIELD_NUMBER: _builtins.int
    POINT_FIELD_NUMBER: _builtins.int
    CIRCLE_FIELD_NUMBER: _builtins.int
    CUSTOM_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def box(self) -> Global___BoundingBox: ...
    @_builtins.property
    def point(self) -> Global___Point2D: ...
    @_builtins.property
    def circle(self) -> Global___Circle: ...
    @_builtins.property
    def custom(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        box: Global___BoundingBox | None = ...,
        point: Global___Point2D | None = ...,
        circle: Global___Circle | None = ...,
        custom: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["box", b"box", "circle", b"circle", "custom", b"custom", "point", b"point", "shape", b"shape"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["box", b"box", "circle", b"circle", "custom", b"custom", "point", b"point", "shape", b"shape"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_shape: _TypeAlias = _typing.Literal["box", "point", "circle", "custom"]  # noqa: Y015
    _WhichOneofArgType_shape: _TypeAlias = _typing.Literal["shape", b"shape"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_shape) -> _WhichOneofReturnType_shape | None: ...

Global___DetectionGeometry: _TypeAlias = DetectionGeometry  # noqa: Y015

@_typing.final
class Detection(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLASS_NAME_FIELD_NUMBER: _builtins.int
    CLASS_ID_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    GEOMETRY_FIELD_NUMBER: _builtins.int
    NORMALIZED_GEOMETRY_FIELD_NUMBER: _builtins.int
    class_name: _builtins.str
    class_id: _builtins.int
    score: _builtins.float
    @_builtins.property
    def geometry(self) -> Global___DetectionGeometry: ...
    @_builtins.property
    def normalized_geometry(self) -> Global___DetectionGeometry: ...
    def __init__(
        self,
        *,
        class_name: _builtins.str = ...,
        class_id: _builtins.int = ...,
        score: _builtins.float = ...,
        geometry: Global___DetectionGeometry | None = ...,
        normalized_geometry: Global___DetectionGeometry | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["geometry", b"geometry", "normalized_geometry", b"normalized_geometry"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["class_id", b"class_id", "class_name", b"class_name", "geometry", b"geometry", "normalized_geometry", b"normalized_geometry", "score", b"score"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Detection: _TypeAlias = Detection  # noqa: Y015

@_typing.final
class StreamConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: _builtins.int
    VIDEO_CODEC_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    SCORE_THRESHOLD_FIELD_NUMBER: _builtins.int
    MAX_DETECTIONS_FIELD_NUMBER: _builtins.int
    stream_id: _builtins.str
    video_codec: _builtins.str
    """例如 "h264" """
    width: _builtins.int
    height: _builtins.int
    score_threshold: _builtins.float
    max_detections: _builtins.int
    def __init__(
        self,
        *,
        stream_id: _builtins.str = ...,
        video_codec: _builtins.str = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
        score_threshold: _builtins.float = ...,
        max_detections: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "max_detections", b"max_detections", "score_threshold", b"score_threshold", "stream_id", b"stream_id", "video_codec", b"video_codec", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamConfig: _TypeAlias = StreamConfig  # noqa: Y015
