"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from artimes_cv.protos.detector import detector_pb2 as _detector_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class DetectorEngineStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> DetectorEngineAsyncStub: ...
    Detect: _grpc.UnaryUnaryMultiCallable[_detector_pb2.DetectRequest, _detector_pb2.DetectReply]
    """输入单帧图像，返回该帧中的目标检测结果。"""
    StreamDetect: _grpc.StreamStreamMultiCallable[_detector_pb2.StreamDetectRequest, _detector_pb2.StreamDetectReply]
    """输入连续视频流，持续返回该流中的目标检测结果。"""

@_typing.type_check_only
class DetectorEngineAsyncStub(DetectorEngineStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Detect: _aio.UnaryUnaryMultiCallable[_detector_pb2.DetectRequest, _detector_pb2.DetectReply]  # type: ignore[assignment]
    """输入单帧图像，返回该帧中的目标检测结果。"""
    StreamDetect: _aio.StreamStreamMultiCallable[_detector_pb2.StreamDetectRequest, _detector_pb2.StreamDetectReply]  # type: ignore[assignment]
    """输入连续视频流，持续返回该流中的目标检测结果。"""

class DetectorEngineServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Detect(
        self,
        request: _detector_pb2.DetectRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_detector_pb2.DetectReply, _abc.Awaitable[_detector_pb2.DetectReply]]:
        """输入单帧图像，返回该帧中的目标检测结果。"""

    @_abc_1.abstractmethod
    def StreamDetect(
        self,
        request_iterator: _MaybeAsyncIterator[_detector_pb2.StreamDetectRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_detector_pb2.StreamDetectReply], _abc.AsyncIterator[_detector_pb2.StreamDetectReply]]:
        """输入连续视频流，持续返回该流中的目标检测结果。"""

def add_DetectorEngineServicer_to_server(servicer: DetectorEngineServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
