"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from artimes_cv.protos.detector import common_pb2 as _common_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ImageFrame(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    """原始图像字节，例如 RGB/BGR 编码后的连续内存或压缩图像"""
    width: _builtins.int
    height: _builtins.int
    format: _builtins.str
    """例如 "rgb8"、"bgr8"、"jpeg"、"png"、"h264" """
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
        format: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "format", b"format", "height", b"height", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ImageFrame: _TypeAlias = ImageFrame  # noqa: Y015

@_typing.final
class DetectRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    FRAME_FIELD_NUMBER: _builtins.int
    SCORE_THRESHOLD_FIELD_NUMBER: _builtins.int
    MAX_DETECTIONS_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    score_threshold: _builtins.float
    max_detections: _builtins.int
    @_builtins.property
    def frame(self) -> Global___ImageFrame: ...
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        frame: Global___ImageFrame | None = ...,
        score_threshold: _builtins.float = ...,
        max_detections: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["frame", b"frame"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["frame", b"frame", "max_detections", b"max_detections", "request_id", b"request_id", "score_threshold", b"score_threshold"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DetectRequest: _TypeAlias = DetectRequest  # noqa: Y015

@_typing.final
class DetectReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    DETECTIONS_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    @_builtins.property
    def detections(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.Detection]: ...
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        detections: _abc.Iterable[_common_pb2.Detection] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detections", b"detections", "request_id", b"request_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DetectReply: _TypeAlias = DetectReply  # noqa: Y015

@_typing.final
class EncodedVideoChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    PTS_MS_FIELD_NUMBER: _builtins.int
    DTS_MS_FIELD_NUMBER: _builtins.int
    KEY_FRAME_FIELD_NUMBER: _builtins.int
    CODEC_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    """编码后的视频载荷，支持 H.264 NALU 或 Annex-B 字节流"""
    pts_ms: _builtins.int
    dts_ms: _builtins.int
    key_frame: _builtins.bool
    codec: _builtins.str
    """例如 "h264" """
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
        pts_ms: _builtins.int = ...,
        dts_ms: _builtins.int = ...,
        key_frame: _builtins.bool = ...,
        codec: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["codec", b"codec", "data", b"data", "dts_ms", b"dts_ms", "key_frame", b"key_frame", "pts_ms", b"pts_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EncodedVideoChunk: _TypeAlias = EncodedVideoChunk  # noqa: Y015

@_typing.final
class StreamDetectRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_FIELD_NUMBER: _builtins.int
    FRAME_FIELD_NUMBER: _builtins.int
    CHUNK_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def config(self) -> _common_pb2.StreamConfig: ...
    @_builtins.property
    def frame(self) -> Global___ImageFrame: ...
    @_builtins.property
    def chunk(self) -> Global___EncodedVideoChunk: ...
    def __init__(
        self,
        *,
        config: _common_pb2.StreamConfig | None = ...,
        frame: Global___ImageFrame | None = ...,
        chunk: Global___EncodedVideoChunk | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["chunk", b"chunk", "config", b"config", "frame", b"frame", "payload", b"payload"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk", b"chunk", "config", b"config", "frame", b"frame", "payload", b"payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["config", "frame", "chunk"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___StreamDetectRequest: _TypeAlias = StreamDetectRequest  # noqa: Y015

@_typing.final
class StreamDetectReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: _builtins.int
    REQUEST_ID_FIELD_NUMBER: _builtins.int
    PTS_MS_FIELD_NUMBER: _builtins.int
    DETECTIONS_FIELD_NUMBER: _builtins.int
    stream_id: _builtins.str
    request_id: _builtins.str
    pts_ms: _builtins.int
    @_builtins.property
    def detections(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.Detection]: ...
    def __init__(
        self,
        *,
        stream_id: _builtins.str = ...,
        request_id: _builtins.str = ...,
        pts_ms: _builtins.int = ...,
        detections: _abc.Iterable[_common_pb2.Detection] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detections", b"detections", "pts_ms", b"pts_ms", "request_id", b"request_id", "stream_id", b"stream_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamDetectReply: _TypeAlias = StreamDetectReply  # noqa: Y015
