"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from artimes_cv.protos.detector import webrtc_detector_pb2 as _webrtc_detector_pb2
from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class WebRtcDetectorEngineStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> WebRtcDetectorEngineAsyncStub: ...
    CreateStream: _grpc.UnaryUnaryMultiCallable[_webrtc_detector_pb2.CreateStreamRequest, _webrtc_detector_pb2.CreateStreamReply]
    """创建基于 WebRTC 的流式检测会话。"""
    UpdateStream: _grpc.UnaryUnaryMultiCallable[_webrtc_detector_pb2.StreamSignal, _webrtc_detector_pb2.UpdateStreamReply]
    """客户端提交 WebRTC answer 或后续 ICE candidate。"""
    StreamDetections: _grpc.UnaryStreamMultiCallable[_webrtc_detector_pb2.StreamDetectionsRequest, _webrtc_detector_pb2.StreamDetectionsReply]
    """订阅指定流会话的检测结果。"""

@_typing.type_check_only
class WebRtcDetectorEngineAsyncStub(WebRtcDetectorEngineStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    CreateStream: _aio.UnaryUnaryMultiCallable[_webrtc_detector_pb2.CreateStreamRequest, _webrtc_detector_pb2.CreateStreamReply]  # type: ignore[assignment]
    """创建基于 WebRTC 的流式检测会话。"""
    UpdateStream: _aio.UnaryUnaryMultiCallable[_webrtc_detector_pb2.StreamSignal, _webrtc_detector_pb2.UpdateStreamReply]  # type: ignore[assignment]
    """客户端提交 WebRTC answer 或后续 ICE candidate。"""
    StreamDetections: _aio.UnaryStreamMultiCallable[_webrtc_detector_pb2.StreamDetectionsRequest, _webrtc_detector_pb2.StreamDetectionsReply]  # type: ignore[assignment]
    """订阅指定流会话的检测结果。"""

class WebRtcDetectorEngineServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def CreateStream(
        self,
        request: _webrtc_detector_pb2.CreateStreamRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_webrtc_detector_pb2.CreateStreamReply, _abc.Awaitable[_webrtc_detector_pb2.CreateStreamReply]]:
        """创建基于 WebRTC 的流式检测会话。"""

    @_abc_1.abstractmethod
    def UpdateStream(
        self,
        request: _webrtc_detector_pb2.StreamSignal,
        context: _ServicerContext,
    ) -> _typing.Union[_webrtc_detector_pb2.UpdateStreamReply, _abc.Awaitable[_webrtc_detector_pb2.UpdateStreamReply]]:
        """客户端提交 WebRTC answer 或后续 ICE candidate。"""

    @_abc_1.abstractmethod
    def StreamDetections(
        self,
        request: _webrtc_detector_pb2.StreamDetectionsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_webrtc_detector_pb2.StreamDetectionsReply], _abc.AsyncIterator[_webrtc_detector_pb2.StreamDetectionsReply]]:
        """订阅指定流会话的检测结果。"""

def add_WebRtcDetectorEngineServicer_to_server(servicer: WebRtcDetectorEngineServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
