# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from artimes_cv.protos.detector import webrtc_detector_pb2 as artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in artimes_cv/protos/detector/webrtc_detector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WebRtcDetectorEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateStream = channel.unary_unary(
                '/vision.v1.WebRtcDetectorEngine/CreateStream',
                request_serializer=artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.CreateStreamRequest.SerializeToString,
                response_deserializer=artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.CreateStreamReply.FromString,
                _registered_method=True)
        self.UpdateStream = channel.unary_unary(
                '/vision.v1.WebRtcDetectorEngine/UpdateStream',
                request_serializer=artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.StreamSignal.SerializeToString,
                response_deserializer=artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.UpdateStreamReply.FromString,
                _registered_method=True)
        self.StreamDetections = channel.unary_stream(
                '/vision.v1.WebRtcDetectorEngine/StreamDetections',
                request_serializer=artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.StreamDetectionsRequest.SerializeToString,
                response_deserializer=artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.StreamDetectionsReply.FromString,
                _registered_method=True)


class WebRtcDetectorEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateStream(self, request, context):
        """创建基于 WebRTC 的流式检测会话。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStream(self, request, context):
        """客户端提交 WebRTC answer 或后续 ICE candidate。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDetections(self, request, context):
        """订阅指定流会话的检测结果。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebRtcDetectorEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateStream': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStream,
                    request_deserializer=artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.CreateStreamRequest.FromString,
                    response_serializer=artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.CreateStreamReply.SerializeToString,
            ),
            'UpdateStream': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStream,
                    request_deserializer=artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.StreamSignal.FromString,
                    response_serializer=artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.UpdateStreamReply.SerializeToString,
            ),
            'StreamDetections': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDetections,
                    request_deserializer=artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.StreamDetectionsRequest.FromString,
                    response_serializer=artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.StreamDetectionsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vision.v1.WebRtcDetectorEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vision.v1.WebRtcDetectorEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WebRtcDetectorEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vision.v1.WebRtcDetectorEngine/CreateStream',
            artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.CreateStreamRequest.SerializeToString,
            artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.CreateStreamReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vision.v1.WebRtcDetectorEngine/UpdateStream',
            artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.StreamSignal.SerializeToString,
            artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.UpdateStreamReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDetections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vision.v1.WebRtcDetectorEngine/StreamDetections',
            artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.StreamDetectionsRequest.SerializeToString,
            artimes__cv_dot_protos_dot_detector_dot_webrtc__detector__pb2.StreamDetectionsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
