"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from artimes_cv.protos.detector import common_pb2 as _common_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class IceServer(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    URLS_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    CREDENTIAL_FIELD_NUMBER: _builtins.int
    username: _builtins.str
    credential: _builtins.str
    @_builtins.property
    def urls(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        urls: _abc.Iterable[_builtins.str] | None = ...,
        username: _builtins.str = ...,
        credential: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["credential", b"credential", "urls", b"urls", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IceServer: _TypeAlias = IceServer  # noqa: Y015

@_typing.final
class SessionDescription(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    SDP_FIELD_NUMBER: _builtins.int
    type: _builtins.str
    """"offer" or "answer" """
    sdp: _builtins.str
    def __init__(
        self,
        *,
        type: _builtins.str = ...,
        sdp: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sdp", b"sdp", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SessionDescription: _TypeAlias = SessionDescription  # noqa: Y015

@_typing.final
class IceCandidate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CANDIDATE_FIELD_NUMBER: _builtins.int
    SDP_MID_FIELD_NUMBER: _builtins.int
    SDP_MLINE_INDEX_FIELD_NUMBER: _builtins.int
    candidate: _builtins.str
    sdp_mid: _builtins.str
    sdp_mline_index: _builtins.int
    def __init__(
        self,
        *,
        candidate: _builtins.str = ...,
        sdp_mid: _builtins.str = ...,
        sdp_mline_index: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["candidate", b"candidate", "sdp_mid", b"sdp_mid", "sdp_mline_index", b"sdp_mline_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IceCandidate: _TypeAlias = IceCandidate  # noqa: Y015

@_typing.final
class CreateStreamRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def config(self) -> _common_pb2.StreamConfig: ...
    def __init__(
        self,
        *,
        config: _common_pb2.StreamConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateStreamRequest: _TypeAlias = CreateStreamRequest  # noqa: Y015

@_typing.final
class CreateStreamReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: _builtins.int
    OFFER_FIELD_NUMBER: _builtins.int
    ICE_SERVERS_FIELD_NUMBER: _builtins.int
    stream_id: _builtins.str
    @_builtins.property
    def offer(self) -> Global___SessionDescription: ...
    @_builtins.property
    def ice_servers(self) -> _containers.RepeatedCompositeFieldContainer[Global___IceServer]: ...
    def __init__(
        self,
        *,
        stream_id: _builtins.str = ...,
        offer: Global___SessionDescription | None = ...,
        ice_servers: _abc.Iterable[Global___IceServer] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["offer", b"offer"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ice_servers", b"ice_servers", "offer", b"offer", "stream_id", b"stream_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateStreamReply: _TypeAlias = CreateStreamReply  # noqa: Y015

@_typing.final
class StreamSignal(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: _builtins.int
    ANSWER_FIELD_NUMBER: _builtins.int
    ICE_CANDIDATE_FIELD_NUMBER: _builtins.int
    stream_id: _builtins.str
    @_builtins.property
    def answer(self) -> Global___SessionDescription: ...
    @_builtins.property
    def ice_candidate(self) -> Global___IceCandidate: ...
    def __init__(
        self,
        *,
        stream_id: _builtins.str = ...,
        answer: Global___SessionDescription | None = ...,
        ice_candidate: Global___IceCandidate | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["answer", b"answer", "ice_candidate", b"ice_candidate", "signal", b"signal"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["answer", b"answer", "ice_candidate", b"ice_candidate", "signal", b"signal", "stream_id", b"stream_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_signal: _TypeAlias = _typing.Literal["answer", "ice_candidate"]  # noqa: Y015
    _WhichOneofArgType_signal: _TypeAlias = _typing.Literal["signal", b"signal"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_signal) -> _WhichOneofReturnType_signal | None: ...

Global___StreamSignal: _TypeAlias = StreamSignal  # noqa: Y015

@_typing.final
class UpdateStreamReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ICE_CANDIDATES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ice_candidates(self) -> _containers.RepeatedCompositeFieldContainer[Global___IceCandidate]: ...
    def __init__(
        self,
        *,
        ice_candidates: _abc.Iterable[Global___IceCandidate] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ice_candidates", b"ice_candidates"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateStreamReply: _TypeAlias = UpdateStreamReply  # noqa: Y015

@_typing.final
class StreamDetectionsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: _builtins.int
    stream_id: _builtins.str
    def __init__(
        self,
        *,
        stream_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stream_id", b"stream_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamDetectionsRequest: _TypeAlias = StreamDetectionsRequest  # noqa: Y015

@_typing.final
class StreamDetectionsReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STREAM_ID_FIELD_NUMBER: _builtins.int
    REQUEST_ID_FIELD_NUMBER: _builtins.int
    PTS_MS_FIELD_NUMBER: _builtins.int
    DETECTIONS_FIELD_NUMBER: _builtins.int
    stream_id: _builtins.str
    request_id: _builtins.str
    pts_ms: _builtins.int
    @_builtins.property
    def detections(self) -> _containers.RepeatedCompositeFieldContainer[_common_pb2.Detection]: ...
    def __init__(
        self,
        *,
        stream_id: _builtins.str = ...,
        request_id: _builtins.str = ...,
        pts_ms: _builtins.int = ...,
        detections: _abc.Iterable[_common_pb2.Detection] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detections", b"detections", "pts_ms", b"pts_ms", "request_id", b"request_id", "stream_id", b"stream_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamDetectionsReply: _TypeAlias = StreamDetectionsReply  # noqa: Y015
