# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: artimes_cv/protos/detector/webrtc_detector.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'artimes_cv/protos/detector/webrtc_detector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from artimes_cv.protos.detector import common_pb2 as artimes__cv_dot_protos_dot_detector_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0artimes_cv/protos/detector/webrtc_detector.proto\x12\tvision.v1\x1a\'artimes_cv/protos/detector/common.proto\"?\n\tIceServer\x12\x0c\n\x04urls\x18\x01 \x03(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x12\n\ncredential\x18\x03 \x01(\t\"/\n\x12SessionDescription\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0b\n\x03sdp\x18\x02 \x01(\t\"K\n\x0cIceCandidate\x12\x11\n\tcandidate\x18\x01 \x01(\t\x12\x0f\n\x07sdp_mid\x18\x02 \x01(\t\x12\x17\n\x0fsdp_mline_index\x18\x03 \x01(\x05\">\n\x13\x43reateStreamRequest\x12\'\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x17.vision.v1.StreamConfig\"\x7f\n\x11\x43reateStreamReply\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12,\n\x05offer\x18\x02 \x01(\x0b\x32\x1d.vision.v1.SessionDescription\x12)\n\x0bice_servers\x18\x03 \x03(\x0b\x32\x14.vision.v1.IceServer\"\x8e\x01\n\x0cStreamSignal\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12/\n\x06\x61nswer\x18\x02 \x01(\x0b\x32\x1d.vision.v1.SessionDescriptionH\x00\x12\x30\n\rice_candidate\x18\x03 \x01(\x0b\x32\x17.vision.v1.IceCandidateH\x00\x42\x08\n\x06signal\"D\n\x11UpdateStreamReply\x12/\n\x0eice_candidates\x18\x01 \x03(\x0b\x32\x17.vision.v1.IceCandidate\",\n\x17StreamDetectionsRequest\x12\x11\n\tstream_id\x18\x01 \x01(\t\"x\n\x15StreamDetectionsReply\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x0e\n\x06pts_ms\x18\x03 \x01(\x04\x12(\n\ndetections\x18\x04 \x03(\x0b\x32\x14.vision.v1.Detection2\x87\x02\n\x14WebRtcDetectorEngine\x12L\n\x0c\x43reateStream\x12\x1e.vision.v1.CreateStreamRequest\x1a\x1c.vision.v1.CreateStreamReply\x12\x45\n\x0cUpdateStream\x12\x17.vision.v1.StreamSignal\x1a\x1c.vision.v1.UpdateStreamReply\x12Z\n\x10StreamDetections\x12\".vision.v1.StreamDetectionsRequest\x1a .vision.v1.StreamDetectionsReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'artimes_cv.protos.detector.webrtc_detector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ICESERVER']._serialized_start=104
  _globals['_ICESERVER']._serialized_end=167
  _globals['_SESSIONDESCRIPTION']._serialized_start=169
  _globals['_SESSIONDESCRIPTION']._serialized_end=216
  _globals['_ICECANDIDATE']._serialized_start=218
  _globals['_ICECANDIDATE']._serialized_end=293
  _globals['_CREATESTREAMREQUEST']._serialized_start=295
  _globals['_CREATESTREAMREQUEST']._serialized_end=357
  _globals['_CREATESTREAMREPLY']._serialized_start=359
  _globals['_CREATESTREAMREPLY']._serialized_end=486
  _globals['_STREAMSIGNAL']._serialized_start=489
  _globals['_STREAMSIGNAL']._serialized_end=631
  _globals['_UPDATESTREAMREPLY']._serialized_start=633
  _globals['_UPDATESTREAMREPLY']._serialized_end=701
  _globals['_STREAMDETECTIONSREQUEST']._serialized_start=703
  _globals['_STREAMDETECTIONSREQUEST']._serialized_end=747
  _globals['_STREAMDETECTIONSREPLY']._serialized_start=749
  _globals['_STREAMDETECTIONSREPLY']._serialized_end=869
  _globals['_WEBRTCDETECTORENGINE']._serialized_start=872
  _globals['_WEBRTCDETECTORENGINE']._serialized_end=1135
# @@protoc_insertion_point(module_scope)
